"""Add role to users and update action status

Revision ID: 16120a6095b1
Revises: 4ce4e33233f6
Create Date: 2025-10-25 21:19:42.910698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16120a6095b1'
down_revision = '4ce4e33233f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
