"""Initial migration

Revision ID: cfb6e27a596b
Revises: 
Create Date: 2025-10-18 11:57:46.826172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb6e27a596b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('member_since', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('issues_reported', sa.Integer(), nullable=True),
    sa.Column('alerts_responded', sa.Integer(), nullable=True),
    sa.Column('community_impact', sa.Integer(), nullable=True),
    sa.Column('trees_planted', sa.Integer(), nullable=True),
    sa.Column('impact_points', sa.Integer(), nullable=True),
    sa.Column('issues_this_month', sa.Integer(), nullable=True),
    sa.Column('alerts_this_month', sa.Integer(), nullable=True),
    sa.Column('trees_this_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_user_achievements_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    op.drop_table('profiles')
    op.drop_table('achievements')
    # ### end Alembic commands ###
